"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import Header from "@/app/components/Header";
import LoadingIndicator from "@/app/components/LoadingIndicator";
import Pagination from "@/app/components/Pagination";
import Sidebar from "@/app/components/Sidebar";
import { fetchJson } from "@/lib/fetch";

type Product = { id: number; name: string; code: string }; type Master = { id: number; name: string; commonTypeName: string }; type Variant = { id: number; sku: string; price: string | number; createdAt: string; updatedAt: string; product: Product; color: Master; size: Master };
export default function ProductVariantsPage() {
  const [items, setItems] = useState<Variant[]>([]); const [products, setProducts] = useState<Product[]>([]); const [masters, setMasters] = useState<Master[]>([]); const [search, setSearch] = useState(""); const [productId, setProductId] = useState(""); const [colorId, setColorId] = useState(""); const [sizeId, setSizeId] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const query = new URLSearchParams({ page: String(page), limit: "10", ...(search ? { search } : {}), ...(productId ? { productId } : {}), ...(colorId ? { colorId } : {}), ...(sizeId ? { sizeId } : {}) }); const data = await fetchJson<{ items: Variant[]; total: number }>(`/api/product-variants?${query}`); setItems(data.items); setTotal(data.total); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load variants"); } finally { setLoading(false); } };
  useEffect(() => { Promise.all([fetchJson<{ items: Product[] }>("/api/products?page=1&pageSize=50"), fetchJson<Master[]>("/api/common-masters")]).then(([productData, masterData]) => { setProducts(productData.items); setMasters(masterData); }).catch((e) => setError(e.message)); }, []); useEffect(() => { void load(); }, [page, productId, colorId, sizeId]);
  const colors = masters.filter((m) => m.commonTypeName.toLowerCase().includes("color")); const sizes = masters.filter((m) => m.commonTypeName.toLowerCase().includes("size"));
  async function remove(id: number) { if (!window.confirm("Delete this product variant?")) return; try { await fetchJson(`/api/product-variants/${id}`, { method: "DELETE" }); void load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete variant"); } }
  function clear() { setSearch(""); setProductId(""); setColorId(""); setSizeId(""); setPage(1); }
  return <div className="dashboard-shell"><Sidebar /><main className="dashboard-main"><Header eyebrow="Catalog" title="Product variants" actions={<Link className="primary-button header-action" href="/product-variants/create">+ Add variant</Link>} /><div className="dashboard-content"><div className="section-heading"><div><h2>Product variants</h2><p className="muted">Manage color and size combinations without inventory data.</p></div></div><section className="panel product-panel"><div className="product-filters variant-filters"><input value={search} placeholder="Search product or SKU" onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && (setPage(1), void load())} /><select value={productId} onChange={(e) => { setProductId(e.target.value); setPage(1); }}><option value="">All products</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name} ({p.code})</option>)}</select><select value={colorId} onChange={(e) => { setColorId(e.target.value); setPage(1); }}><option value="">All colors</option>{colors.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><select value={sizeId} onChange={(e) => { setSizeId(e.target.value); setPage(1); }}><option value="">All sizes</option>{sizes.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><button className="outline-button" type="button" onClick={() => { setPage(1); void load(); }}>Search</button><button className="outline-button" type="button" onClick={clear}>Clear</button></div>{error && <p className="form-error">{error}</p>}{loading ? <LoadingIndicator label="Loading variants" /> : items.length === 0 ? <div className="empty-state"><strong>No product variants found</strong><p className="muted">Create a color and size combination for a product.</p></div> : <div className="product-table-wrap"><table className="product-table"><thead><tr><th>Product</th><th>Product Code</th><th>Color</th><th>Size</th><th>SKU</th><th>Price</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.product.name}</strong></td><td>{item.product.code}</td><td>{item.color.name}</td><td>{item.size.name}</td><td>{item.sku}</td><td>{Number(item.price).toFixed(2)}</td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td>{new Date(item.updatedAt).toLocaleDateString()}</td><td><div className="row-actions"><Link href={`/product-variants/${item.id}`}>View</Link><Link href={`/product-variants/${item.id}/edit`}>Edit</Link><button type="button" className="danger-button" onClick={() => remove(item.id)}>Delete</button></div></td></tr>)}</tbody></table></div>}<Pagination page={page} pageCount={Math.max(1, Math.ceil(total / 10))} onPageChange={setPage} /></section></div></main></div>;
}
